name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ij: [ 2022.1.4, 2022.3.3 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build and verify
        run: ./gradlew clean buildPlugin test verifyPlugin verifypluginconfiguration -PpluginVerifyProductDescriptor=true -PpluginNeedsLicense=false -PpluginIdeaVersion=IC-${{ matrix.ij }} --warning-mode all
      - name: Upload build package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./build/distributions/*.zip
